buildandrun:
	@g++ -o part1 part1/part1.cpp 
	# && cat input | ./part1
	# @g++ -o part2 part2/part2.cpp && cat input | ./part2
build:
	# @g++ -o part1 part1/part1.cpp
	# @g++ -o part2 part2/part2.cpp
run:
	# @./part1
	# @./part2
